project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - href: Final_Project_Text_And_Code.qmd
        text: Final Project
        icon: code
      
format:
  html:
    backgroundcolor: "#FF5F1F"
    fontcolor: "White"
    linkcolor: "DarkBlue"
    mainfont: "TimesNewRoman"
    fontsize: 20px
    theme: [cosmo, styles.scss]

